CREATE TABLE IF NOT EXISTS `pit` (
`id` int(11) NOT NULL auto_increment,
`id_user` int(11) NOT NULL,
`pit` int(11) NOT NULL,
`name` varchar(20) default NULL,
`time` int(11) NOT NULL,
`dom` int(11) NOT NULL,
`igra` int(11) NOT NULL,
`sila` int(11) NOT NULL,
`sila_time` int(11) NOT NULL,
`zdorov` int(11) NOT NULL,
`zdorov_time` int(11) NOT NULL,
`zashita` int(11) NOT NULL,
`zashita_time` int(11) NOT NULL,
`boi` int(11) NOT NULL,
`win` int(11) NOT NULL,
`lose` int(11) NOT NULL,
`timenap` int(11) NOT NULL,
PRIMARY KEY  (`id`)) ENGINE=MyISAM  DEFAULT CHARSET=utf8;