 ALTER TABLE `user` ADD `pers` varchar(50) DEFAULT '1:1' COMMENT 'Персонаж';
 ALTER TABLE `user` ADD `pers_time` int(11) DEFAULT '0' COMMENT 'Время жизни персонажа';

CREATE TABLE IF NOT EXISTS `gala_person` (
  `id` int(11) NOT NULL,
  `type` varchar(4) NOT NULL,
  `style` varchar(256) NOT NULL,
  `style_small` varchar(128) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


INSERT INTO `gala_person` (`id`, `type`, `style`, `style_small`) VALUES
(1, 'foot', '', ''),
(2, 'foot', '', ''),
(3, 'foot', '', ''),
(4, 'foot', '', ''),
(5, 'foot', '', ''),
(6, 'foot', '', ''),
(7, 'foot', '', ''),
(8, 'foot', '', ''),
(9, 'foot', '', ''),
(10, 'foot', '', ''),
(12, 'foot', '', ''),
(13, 'foot', '', ''),
(14, 'foot', '', ''),
(15, 'foot', '', ''),
(16, 'foot', '', ''),
(17, 'foot', '', ''),
(18, 'foot', '', ''),
(19, 'foot', '', ''),
(20, 'foot', '', ''),
(21, 'foot', '', ''),
(22, 'foot', '', ''),
(1, 'head', 'margin-top: -12px;', 'margin-top: -6px;'),
(2, 'head', 'margin-top: -12px;', 'margin-top: -6px;'),
(3, 'head', 'margin-top: -12px;', 'margin-top: -6px;'),
(4, 'head', 'margin-top: -12px;', 'margin-top: -6px;'),
(5, 'head', 'margin-top: -8px;', 'margin-top: -4px;'),
(6, 'head', 'margin-top: -9px;', 'margin-top: -4px;'),
(7, 'head', 'margin-top: -28px;', 'margin-top: -14px;'),
(8, 'head', 'margin-top: -14px;', 'margin-top: -7px;'),
(9, 'head', 'margin-top: -8px;', 'margin-top: -4px;'),
(10, 'head', 'margin-top: -8px;', 'margin-top: -4px;'),
(11, 'head', 'margin-top: -8px;', 'margin-top: -4px;'),
(12, 'head', 'margin-top: -8px;', 'margin-top: -4px;'),
(13, 'head', 'margin-top: -7px;', 'margin-top: -4px;'),
(14, 'head', 'margin-top: -7px;', 'margin-top: -4px;'),
(15, 'head', 'margin-top: -7px;', 'margin-top: -4px;'),
(16, 'head', 'margin-top: -7px;', 'margin-top: -4px;'),
(17, 'head', 'margin-top: -12px;', 'margin-top: -6px;'),
(18, 'head', 'margin-top: -8px;', 'margin-top: -4px;'),
(19, 'head', 'margin-top: -13px;', 'margin-top: -6px;'),
(20, 'head', 'margin-top: -11px;', 'margin-top: -5px;'),
(21, 'head', 'margin-top: -28px;', 'margin-top: -14px;'),
(22, 'head', 'margin-top: -33px;', 'margin-top: -17px;'),
(23, 'head', 'margin-top: -14px;', 'margin-top: -7px;'),
(25, 'head', 'margin-top: -21px;', 'margin-top: -11px;');
