CREATE TABLE `farm_user` (
`uid` int(11) NOT NULL DEFAULT '0',
`posadka` int(11) NOT NULL DEFAULT '0',
`posadka_1` enum('1','0') NOT NULL DEFAULT '0',
`posadka_2` enum('1','0') NOT NULL DEFAULT '0',
`posadka_3` enum('1','0') NOT NULL DEFAULT '0',
`poliv` int(11) NOT NULL DEFAULT '0',
`poliv_1` enum('1','0') NOT NULL DEFAULT '0',
`poliv_2` enum('1','0') NOT NULL DEFAULT '0',
`poliv_3` enum('1','0') NOT NULL DEFAULT '0',
`udobrenie` int(11) NOT NULL DEFAULT '0',
`udobrenie_1` enum('1','0') NOT NULL DEFAULT '0',
`udobrenie_2` enum('1','0') NOT NULL DEFAULT '0',
`udobrenie_3` enum('1','0') NOT NULL DEFAULT '0',
`gems` int(11) NOT NULL DEFAULT '0',
`xp` int(11) NOT NULL DEFAULT '100',
`gold` int(11) NOT NULL DEFAULT '10000',
`exp` int(11) NOT NULL DEFAULT '0',
`lеvеl` int(11) NOT NULL DEFAULT '0',
`k_poliv` int(11) NOT NULL DEFAULT '0',
`k_posadka` int(11) NOT NULL DEFAULT '0',
`k_posadka_time` int(11) NOT NULL DEFAULT '0',
`k_poliv_time` int(11) NOT NULL DEFAULT '0',
`zabor_time` int(11) NOT NULL DEFAULT '0',
`teplica` enum('1','0') NOT NULL DEFAULT '0',
`razvedka` enum('1','0') NOT NULL DEFAULT '0',
`selection` enum('0','1','2','3','4','5') NOT NULL DEFAULT '0',
PRIMARY KEY (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;