ALTER TABLE `user` ADD `ikey_reit` VARCHAR( 100 ) DEFAULT '0';
ALTER TABLE `user` ADD `z1` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z2` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z3` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z4` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z5` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z6` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z7` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z8` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z9` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z10` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z11` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z12` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z13` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z1_p` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z1_lock` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z2_p` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z2_lock` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z3_p` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z3_lock` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z4_p` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z4_lock` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z5_p` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z5_lock` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z6_p` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z6_lock` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z7_p` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z7_lock` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z8_p` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z8_lock` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z9_p` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z9_lock` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z10_p` INT( 11 ) NOT NULL;
ALTER TABLE `user` ADD `z10_lock` INT( 11 ) NOT NULL;








