<?
if($oper == 1)$oper_name = "Мегафон (Россия)";
if($oper == 2)$oper_name = "Билайн (Россия)";
if($oper == 3)$oper_name = "Utel (Россия)";
if($oper == 4)$oper_name = "БайкалВестКом (Россия)";
if($oper == 5)$oper_name = "МТС (Россия)";
if($oper == 6)$oper_name = "TELE2 (Россия)";
if($oper == 7)$oper_name = "МОТИВ (Россия)";
if($oper == 8)$oper_name = "Енисейтелеком (Россия)";
if($oper == 9)$oper_name = "НСС (Россия)";
if($oper == 10)$oper_name = "СМАРТС (Россия)";
if($oper == 11)$oper_name = "СТЕК GSM (Россия)";
if($oper == 12)$oper_name = "Татинком-Т (Россия)";
if($oper == 13)$oper_name = "Ульяновск GSM (Россия)";
if($oper == 14)$oper_name = "НТК (Россия)";
if($oper == 15)$oper_name = "СКАЙЛИНК (Россия)";
if($oper == 16)$oper_name = "Цифровая экспансия (Россия)";
if($oper == 17)$oper_name = "ИНДИГО (Таджикистан)";
if($oper == 18)$oper_name = "Emt (Эстония)";
if($oper == 19)$oper_name = "Elisa (Эстония)";
if($oper == 20)$oper_name = "Tele-2 (Эстония)";
if($oper == 21)$oper_name = "Bite (Литва)";
if($oper == 22)$oper_name = "Omnitel (Литва)";
if($oper == 23)$oper_name = "Tele-2 (Литва)";
if($oper == 24)$oper_name = "Tele-2 (Латвия)";
if($oper == 25)$oper_name = "Lmt (Латвия)";
if($oper == 26)$oper_name = "Киевстар (Украина)";
if($oper == 27)$oper_name = "UMC (Украина)";
if($oper == 28)$oper_name = "life:) (Украина)";
if($oper == 29)$oper_name = "WellCOM (Украина)";
if($oper == 30)$oper_name = "UTEL (Украина)";
if($oper == 31)$oper_name = "Прибалтийские операторы";
if($oper == 32)$oper_name = "Opera Mini";
if($oper == 33)$oper_name = "Beeline (Казахстан)";
if($oper == 34)$oper_name = "Экстел GSM ";
if($oper == 35)$oper_name = "Babilon GSM (Таджикистан)";
if($oper == 36)$oper_name = "БеСТ (Беларусь)";
if($oper == 37)$oper_name = "Сотовая Связь Улан-Уде (Россия)";
if($oper == 38)$oper_name = "AQUAFON Абхазия-GSM (Россия)";
if($oper == 39)$oper_name = "MegaCom KG (Киргизия)";
if($oper == 40)$oper_name = "Kyrgyztelecom (Киргизия)";
if($oper == 41)$oper_name = "BiTel (Киргизия)";
if($oper == 42)$oper_name = "ON GSM (Россия)";
if($oper == 43)$oper_name = "VELCOM (Белорусь)";
if($oper == 44)$oper_name = "Алтайсвязь (Россия)";
if($oper == 45)$oper_name = "Тамбов GSM (Россия)";
if($oper == 46)$oper_name = "БашСел (Россия)";
if($oper == 47)$oper_name = "ДальСвязь (Россия)";
if($oper == 48)$oper_name = "Оренбург GSM (Россия)";
if($oper == 49)$oper_name = "Скай Мобайл (Россия)";
if($oper == 50)$oper_name = "УралСвязьИнформ (Россия)";
if($oper == 51)$oper_name = "MLT (Tаджикистан)";
if($oper == 52)$oper_name = "BiMoCom";
if($oper == 53)$oper_name = "K-Mobile";
if($oper == 54)$oper_name = "MTN (ЮАР)";
if($oper == 55)$oper_name = "Cell (ЮАР)";
if($oper == 56)$oper_name = "Vodacom (ЮАР)";
if($oper == 57)$oper_name = "Magticom (Грузия)";
if($oper == 58)$oper_name = "Geocell (Грузия)";
if($oper == 59)$oper_name = "Orange (Израиль)";
if($oper == 60)$oper_name = "Cellcom (Израиль)";
if($oper == 61)$oper_name = "Voxtel GSM (Молдова)";
if($oper == 62)$oper_name = "Moldcell (Молдова)";
if($oper == 63)$oper_name = "GLOBUL (Болгария)";
if($oper == 64)$oper_name = "M-TEL GSM (Болгария)";
if($oper == 65)$oper_name = "China Mobile (Китай)";
if($oper == 66)$oper_name = "Orange (Румыния)";
if($oper == 67)$oper_name = "Vodafone (Румыния)";
if($oper == 68)$oper_name = "Indosat (Индонезия)";
if($oper == 69)$oper_name = "proXL (Индонезия)";
if($oper == 70)$oper_name = "T-SEL (Индонезия)";
if($oper == 71)$oper_name = "Orange (Франция)";
if($oper == 72)$oper_name = "SFR (Франция)";
if($oper == 73)$oper_name = "Bouygues Telecom (Франция)";
if($oper == 74)$oper_name = "Orange (Великобритания)";
if($oper == 75)$oper_name = "O2 (Великобритания)";
if($oper == 76)$oper_name = "T-Mobile (Великобритания)";
if($oper == 77)$oper_name = "Dishnet (Индия)";
if($oper == 78)$oper_name = "Vodafone (Великобритания)";
if($oper == 79)$oper_name = "HUTCH (Индия)";
if($oper == 80)$oper_name = "idEA (Индия)";
if($oper == 81)$oper_name = "MTNL (Индия)";
if($oper == 82)$oper_name = "АКОС (Россия)";
if($oper == 83)$oper_name = "Airtel (Индия)";
if($oper == 84)$oper_name = "Vodafone (Италия)";
if($oper == 85)$oper_name = "Telecom Italia Mobile (Италия)";
if($oper == 86)$oper_name = "T-Mobile (США)";
if($oper == 87)$oper_name = "AT T (США)";
if($oper == 88)$oper_name = "Mobilkom (Австрия)";
if($oper == 89)$oper_name = "Azercell Telecom (Aзербайджан)";
if($oper == 90)$oper_name = "Bakcell (Aзербайджан)";
if($oper == 91)$oper_name = "Nar Mobile (Aзебайджан)";
if($oper == 92)$oper_name = "Topnet 3G (Сербия и Черногория)";
if($oper == 93)$oper_name = "TELEKOM SRBIJA (Сербия и Черногория)";
if($oper == 94)$oper_name = "MOBTEL (Югославия)";
if($oper == 95)$oper_name = "Vodafone (Ирландия)";
if($oper == 96)$oper_name = "Vipnet (Хорватия)";
if($oper == 97)$oper_name = "Vivacell (Армения)";
if($oper == 98)$oper_name = "E-Plus (Германия)";
if($oper == 99)$oper_name = "O2 DE (Германия)";
if($oper == 100)$oper_name = "T-Mobile DE (Германия)";
if($oper == 101)$oper_name = "Vodafone DE (Германия)";
if($oper == 102)$oper_name = "WIND (Италия)";
if($oper == 103)$oper_name = "Eventis (Молдавия)";
if($oper == 104)$oper_name = "Vodafone (Испания)";
if($oper == 105)$oper_name = "Orange (Испания)";
if($oper == 106)$oper_name = "Euskaltel (Испания)";
if($oper == 107)$oper_name = "R (Испания)";
if($oper == 108)$oper_name = "Telecable (Испания)";
if($oper == 109)$oper_name = "KPN (Голландия)";
if($oper == 110)$oper_name = "T-Mobile (Голландия)";
if($oper == 111)$oper_name = "Vodafone (Голландия)";
if($oper == 112)$oper_name = "Orange (Голландия)";
if($oper == 113)$oper_name = "Telfort (Голландия)";
if($oper == 114)$oper_name = "Tele2 (Голландия)";
if($oper == 115)$oper_name = "O2 (Чехия)";
if($oper == 116)$oper_name = "T-Mobile (Чехия)";
if($oper == 117)$oper_name = "KCELL (Казахстан)";
if($oper == 118)$oper_name = "Компьютеры";
?>